name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test rig
        uses: actions/checkout@v3
        with:
          ref: unit-testing-rig
        
      - name: Check out main package
        uses: actions/checkout@v3
        with:
          path: Packages/com.rmMinusR.items
        
      - name: Unity - Fetch license
        uses: game-ci/unity-request-activation-file@v2.0.0
        
      - name: Unity - Test runner
        id: runTests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
      
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.runTests.outputs.coveragePath }}